### ISSUE TITLE
Create Branch release-ranger-2.4.0

### ISSUE THREAD

**Issue by hamdiazz** [TOSIT-IO/ranger#5]
Hello,
We have found that with version 2.0.0 of Ranger, we can not synchronise deleted users on LDAP. Also, the latest stable version of Apache Ranger is 2.4.0.

I forked this version, built Ranger 2.4.0 and after a few small changes in install.properties of Ranger, successfully deployed.
Could you please create the branch for Ranger 2.4.0, so I can create an MR to fix the install.properties errors I had during deployment.

Thanks,

**Comment by Pierrotws** [comment]
Apache Ranger 2.4.0 is already planned for next TDP Stack based on hadoop 3.3.

Backport of 2.4.0 is not planned on current stack (hadoop 3.1.1)
